services:
  db:
    image: mysql:8.0
    command: --innodb-buffer-pool-size=50M --innodb-log-buffer-size=8M --innodb-flush-log-at-trx-commit=2 --innodb-file-per-table=1 --max-connections=25
    volumes:
      - db_datas:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_MAX_CONNECTIONS: 25
      MYSQL_TCP_PORT: 3306
    networks:
      - web

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 3000M
    networks:
      - web

networks:
  web:

volumes:
  db_datas:
