services:
  db:
    image: postgres:alpine
    container_name: my_pg
    restart: always
    networks:
      - postgresql
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
    command: postgres -c 'shared_buffers=64MB' -c 'max_connections=10'

  adminer:
    image: adminer:latest
    container_name: adminer_container
    restart: always
    networks:
      - postgresql
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    deploy:
      resources:
        limits:
          memory: 128M

volumes:
  local_pgdata:

networks:
  postgresql:
    driver: bridge
