services:
  redis:
    image: redis:alpine3.20
    container_name: redis_container
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass redispassword
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
